### ISSUE TITLE
linux_64_python3.11.____cpython build failed

### ISSUE THREAD

**Issue by thewchan** [conda-forge/typst-py-feedstock#13]
### Comment:

@conda-forge/typst-py The build for linux_64_python3.11.____cpython failed; I think it just needs to be re-triggered. Thanks!

**Comment by freundTech** [comment]
CI ist running. Let's wait for the result before closing this issue.

**Comment by freundTech** [comment]
Looks like all the builds failed now. Might need rust pinned to an older version?

Don't have much time to investigate right now. Maybe @pavelzw can pick up from here or I'll come back to it later.

**Comment by pavelzw** [comment]
Lets See what happens with #16
